experiment_name: MiniGridTrain
agent_name: MiniGridAgent
wandb_key: null
env_id: MiniGrid-DeceivingRewards-v0
num_env_steps : 10000000
log_dir: /tmp/minigrid_ppo
gamma: 0.99
save_interval: 500
max_time: 86400
num_env_processes: 8
num_steps: 128
num_mini_batch: 4
clip_param: 0.1
ppo_epoch: 3
gae_lambda: 0.95
value_loss_coef: 2.0
entropy_coef: 0.05
max_grad_norm: 0.5
lr: 0.001
feature_extractor_net: CNN
restart_reference_model: null
restart_model: null
value_threshold: 0.02
