agent_name: MontezumaAgent
clip_param: 0.1
clip_rewards: true
cluster: false
com_col_workers: synchronous
com_grad_workers: synchronous
conf: null
entropy_coef: 0.001
env_id: MontezumaRevengeNoFrameskip-v4
episodic_life: false
experiment_name: MontezumaRevengeNoFrameskip-v4
frame_skip: 0
frame_stack: 4
gae_lambda: 0.95
gamma: 0.999
log_dir: /tmp/rnd_ppo
log_interval: 1
lr: 0.0001
max_grad_norm: 50.0
max_time: 86400
nn: CNN
num_col_workers: 1
num_env_processes: 16
num_grad_workers: 1
num_mini_batch: 4
num_steps: 128
ppo_epoch: 4
recurrent_policy: false
restart_model: null
save_interval: 100
seed: 0
start_env_steps: 0
target_env_steps: 100000000
value_loss_coef: 1.0
gamma_intrinsic: 0.999
ext_adv_coeff: 2.0
int_adv_coeff: 1.0
predictor_proportion: 2.0
pre_normalization_steps: 50
wandb_key: b5ef9811ad92fac918facca483c7b6caa73df290
