agent_name: MontezumaAgent
clip_param: 0.1
cluster: false
com_col_workers: synchronous
com_grad_workers: synchronous
conf: null
entropy_coef: 0.001
env_id: MontezumaRevengeNoFrameskip-v4
episodic_life: false
sticky_actions: True
clip_rewards: true
experiment_name: MontezumaRevengeNoFrameskip-v4
frame_skip: 0
frame_stack: 4
gae_lambda: 0.95
gamma: 0.999
log_dir: /tmp/rnd_ppo
log_interval: 1
lr: 0.0001
max_grad_norm: 1.0
max_time: 8640000
feature_extractor_net: CNN
num_col_workers: 1
num_env_processes: 128
num_grad_workers: 1
num_mini_batch: 4
num_steps: 128
ppo_epoch: 4
recurrent_net: null
restart_model: null
save_interval: 100
start_env_steps: 0
target_env_steps: 1_000_000_000
value_loss_coef: 1.0
gamma_intrinsic: 0.99
ext_adv_coeff: 2.0
int_adv_coeff: 1.0
predictor_proportion: 0.25
pre_normalization_steps: 50
wandb_key: null
