env_id: HalfCheetahBulletEnv-v0
experiment_name: HalfCheetahBullet
agent_name: TD3
wandb_key: null
num_env_steps : 1_000_000
log_dir: /tmp/pybullet_td3
frame_skip: 0
frame_stack: 1
feature_extractor_net: MLP
restart_model: null
lr: 1.0e-3
gamma: 0.99
polyak: 0.995
noise: Gauss
max_time: 86400
num_env_processes: 1
mini_batch_size: 100 
update_every: 1 
num_updates: 1
start_steps: 20000
buffer_size: 1_000_000
log_interval: 1
save_interval: 50000
num_grad_workers: 1
num_col_workers: 1 
com_grad_workers: synchronous
com_col_workers: synchronous
