experiment_name: GenChem
agent_name: SAC
num_env_steps : 100_000_000
log_dir: /tmp/genchem_sac
gamma: 0.99
polyak: 0.995
save_interval: 50_000
max_time: 86400
num_env_processes: 1
mini_batch_size: 64
update_every: 1
num_updates: 1
start_steps: 20_000
buffer_size: 300_000
target_update_interval: 8_000
lr: 0.0001
nn: Embedding
recurrent_nets: LSTM
num_grad_workers: 1
num_col_workers: 1
com_grad_workers: synchronous
com_col_workers: synchronous
wandb_key: null
