experiment_name: MontezumaRevengeNoFrameskip-v4
agent_name: AtariAgent
wandb_key: null
env_id: MontezumaRevengeNoFrameskip-v4
num_env_steps : 10_000_000
log_dir: /tmp/atari_ppod
gamma: 0.999
rho: 0.15
phi: 0.0
save_interval: 10000
max_time: 86400
num_env_processes: 128
num_steps: 128
num_mini_batch: 4
clip_param: 0.1
ppo_epoch: 4
gae_lambda: 0.95
value_loss_coef: 1.0
entropy_coef: 0.001
max_grad_norm: 1.0
recurrent_nets: True
lr: 0.00025
nn: CNN
clip_rewards: True
episodic_life: False
frame_skip: 0
frame_stack: 4
num_grad_workers: 1
num_col_workers: 1 
com_grad_workers: synchronous
com_col_workers: synchronous
demos_dir: code_examples/train_atari/ppod/demos/
