num_env_steps : 1000000
log_dir: /tmp/pybullet_sac
gamma: 0.99
polyak: 0.995
save_interval: 50000
max_time: 100000000000000000
num_env_processes: 1
mini_batch_size: 256 
update_every: 1 
num_updates: 1
start_steps: 20000 
buffer_size: 1000000 
lr: 3.0e-4
nn: MLP
frame_skip: 0
frame_stack: 1
env_id: HalfCheetahBulletEnv-v0
num_grad_workers: 1 
num_col_workers: 1 
com_grad_workers: synchronous
com_col_workers: synchronous
