experiment_name: MiniGridTrain
agent_name: MiniGridAgent
wandb_key: b5ef9811ad92fac918facca483c7b6caa73df290
env_id: MiniGrid-DeceivingRewards-v0
num_env_steps : 10000000
log_dir: /tmp/minigrid_ppo
gamma: 0.99
save_interval: 500
max_time: 86400
num_env_processes: 8
num_steps: 128
num_mini_batch: 4
clip_param: 0.1
ppo_epoch: 3
gae_lambda: 0.95
value_loss_coef: 2.0
entropy_coef: 0.01
max_grad_norm: 0.5
lr: 0.0001
initial_reward_threshold: 1.0
feature_extractor_net: CNN
shared_policy_value_network: True
restart_reference_model: null
restart_model: null