name: PPO

# ppo specific config: 
ppo_config:
  lr: 1.0e-4
  eps: 1.0e-8
  gamma: 0.99
  num_epochs: 10
  clip_param: 0.2
  num_mini_batch: 1
  test_every: 1000
  max_grad_norm: 0.5
  entropy_coeff: 0.01
  value_loss_coef: 0.5
  num_test_episodes: 5
  use_clipped_value_loss: True

# default config 
defaults:
  - _self_
  - actor: on_policy
  - storage: gae_buffer
