experiment_name: GenChem
agent_name: PPO_Libinvent
pretrain_lr: 0.001
pretrain_epochs: 10
pretrain_lr_decrease_value: 0.03
pretrain_lr_decrease_period: 500
pretrain_batch_size: 128
pretrain_max_smile_length: 100
pretrain_element_list: [6, 7, 8, 9, 16, 17, 35]
pretrainingset_path: ../../../code_examples/train_genchem/ppo/prior_trainingset
pretrain_max_heavy_atoms: 50
pretrain_min_heavy_atoms: 10
num_env_steps : 1000_000_000
log_dir: /tmp/genchem_ppo
gamma: 0.99
kl_coef: 0.5
save_interval: 10000
max_time: 86400
num_env_processes: 1
num_steps: 200
num_mini_batch: 4
clip_param: 0.1
ppo_epoch: 3
gae_lambda: 0.95
value_loss_coef: 1.0
entropy_coef: 0.01
max_grad_norm: 0.5
lr: 0.001
feature_extractor_net: Embedding
recurrent_net: LSTM
num_grad_workers: 1
num_col_workers: 1 
com_grad_workers: synchronous
com_col_workers: synchronous
wandb_key: null
