env_id: CartPole-v0
num_env_steps : 1000000
log_dir: /tmp/pybullet_mpc
frame_skip: 0
frame_stack: 1
lr: 3.0e-4
n_planner: 2500
planning_depth: 12
ensemble_size: 7
elite_size: 5
dynamics_type: probabilistic
validation_percentage: 0.2
max_time: 86400
num_env_processes: 1
mini_batch_size: 256 
update_every: 250
num_updates: 1
start_steps: 1000
buffer_size: 1000000
save_interval: 50000
num_grad_workers: 1
num_col_workers: 1 
com_grad_workers: synchronous
com_col_workers: synchronous
