env_id: Pendulum-v1
num_env_steps : 50_000
log_dir: /tmp/pybullet_mpc
experiment_name: MPC
agent_name: RS-MPC
wandb_key: null
frame_skip: 0
frame_stack: 1
lr: 1.0e-3
mpc_type: RS
n_planner: 700
horizon: 30
ensemble_size: 5
elite_size: 3
dynamics_type: probabilistic
validation_percentage: 0.2
max_time: 86400
num_env_processes: 1
mini_batch_size: 256 
update_every: 250
test_every: 4
num_updates: 1
start_steps: 5000
buffer_size: 1000000
save_interval: 5
num_grad_workers: 1
num_col_workers: 1 
com_grad_workers: synchronous
com_col_workers: synchronous
