experiment_name: Causal_World
agent_name: PPO
wandb_key: null
num_env_steps : 10_000_000
log_dir: /tmp/causal_world_ppo
gamma: 0.99
save_interval: 10000
max_time: 86400
num_env_processes: 1
num_steps: 128
num_mini_batch: 4
clip_param: 0.1
ppo_epoch: 3
gae_lambda: 0.95
value_loss_coef: 1.0
entropy_coef: 0.01
max_grad_norm: 0.5
lr: 0.00025
nn: MLP
frame_skip: 0
frame_stack: 4
num_grad_workers: 1
num_col_workers: 1 
com_grad_workers: synchronous
com_col_workers: synchronous
