experiment_name: PPOD_AnimalAI
agent_name: AnimalAgent
wandb_key: null
num_env_steps : 10_000_000
log_dir: /tmp/animal_ppod
gamma: 0.998
rho: 0.3
phi: 0.0
save_interval: 100000
max_time: 86400
num_env_processes: 14
num_steps: 1000
num_mini_batch: 7
clip_param: 0.15
ppo_epoch: 4
gae_lambda: 0.95
value_loss_coef: 0.1
max_grad_norm: 0.5
entropy_coef: 0.02
lr: 0.0001
nn: CNN
recurrent_nets: GRU
frame_skip: 2
frame_stack: 4
num_grad_workers: 1
num_col_workers: 1 
com_grad_workers: synchronous
com_col_workers: synchronous
arenas_dir: code_examples/train_animalai/ppod/arenas/
demos_dir: code_examples/train_animalai/ppod/demos/
restart_model: null
