experiment_name: benchmarking_libinvent
agent_name: PPO_Libinvent
num_env_steps : 1000_000_000
log_dir: /tmp/genchem_ppo_libinvent
pretrainingset_path: ../path/to/prior_trainingset
gamma: 0.99
kl_coef: 0.1
save_interval: 10000
max_time: 86400
num_env_processes: 64
num_steps: 120
num_mini_batch: 2
clip_param: 0.1
ppo_epoch: 4
gae_lambda: 0.95
value_loss_coef: 1.0
entropy_coef: 0.005
max_grad_norm: 0.5
lr: 0.0005
recurrent_net: LSTMEncoderDecoder
scaffolds: ["[*:0]N1CCN(CC1)CCCCN[*:1]"]
randomize_scaffolds: False
reaction_filters: []
wandb_key: null
