experiment_name: Obstacle_Tower
agent_name: SAC
wandb_key: null
num_env_steps : 1000000
log_dir: /tmp/obstacle_sac
frame_skip: 2
frame_stack: 4
feature_extractor_net: Fixup
lr: 3.0e-4
gamma: 0.99
polyak: 0.995
max_time: 86400
num_env_processes: 3
recurrent_net: GRU
reward_shape: True
reduced_action_space: True
num_actions: 6
mini_batch_size: 256
update_every: 1 
num_updates: 1
start_steps: 2500
buffer_size: 9000
save_interval: 50000
num_grad_workers: 1
num_col_workers: 1 
com_grad_workers: synchronous
com_col_workers: synchronous
