wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.7.9
      5: 0.10.21
      8:
      - 5
action_noise:
  desc: null
  value: false
agent_name:
  desc: null
  value: RS-MPC
beta:
  desc: null
  value: 0.5
buffer_size:
  desc: null
  value: 1000000
cluster:
  desc: null
  value: false
com_col_workers:
  desc: null
  value: synchronous
com_grad_workers:
  desc: null
  value: synchronous
conf:
  desc: null
  value: null
env_id:
  desc: null
  value: Pendulum-v0
eps:
  desc: null
  value: 1.0e-08
experiment_name:
  desc: null
  value: MPC
frame_skip:
  desc: null
  value: 0
frame_stack:
  desc: null
  value: 1
gamma:
  desc: null
  value: 1.0
hidden_size:
  desc: null
  value: 500
horizon:
  desc: null
  value: 30
iter_update_steps:
  desc: null
  value: 3
k_best:
  desc: null
  value: 5
learn_reward_function:
  desc: null
  value: 1
log_dir:
  desc: null
  value: /tmp/pybullet_mpc
log_interval:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.001
max_time:
  desc: null
  value: 86400
mini_batch_size:
  desc: null
  value: 256
mpc_type:
  desc: null
  value: RS
n_planner:
  desc: null
  value: 500
num_col_workers:
  desc: null
  value: 1
num_env_processes:
  desc: null
  value: 1
num_env_steps:
  desc: null
  value: 20000
num_grad_workers:
  desc: null
  value: 1
num_updates:
  desc: null
  value: 1
recurrent_policy:
  desc: null
  value: false
restart_model:
  desc: null
  value: null
save_interval:
  desc: null
  value: 5
start_steps:
  desc: null
  value: 5000
test_every:
  desc: null
  value: 4
update_alpha:
  desc: null
  value: 0.0
update_every:
  desc: null
  value: 250
wandb_key:
  desc: null
  value: 16d18880bf755b96f6114e4fa2d0a7a5a00a3570
